### ISSUE TITLE
Implement /register Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#30]
# Issue: Implement /register Endpoint

## Description

We need to implement the /register endpoint in the Vault backend. This endpoint is responsible for temporarily registering a new user. It will then wait for the user to confirm the phone number and deploy their account contract.

## Details

- **Method:** POST
- **Path:** /register
- **Summary:** Register a phone number and a StarkNet address that will need to be activated by validating the phone number and deploying the contract.

### Request Body:

```json
{
    "phone_number": "+1234567890",
    "address": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
    "first_name": "John",
    "last_name": "Doe"
}
```

- **phone_number:** A string representing the user's phone number in E.164 format.
- **address:** A string representing the user's StarkNet address in hexadecimal format.
- **first_name:** A string representing the user's first name.
- **last_name:** A string representing the user's last name.

### Response:

- **Status Code:** 200
- **Description:** Registration successful
- **Content Type:** application/json
- **Body:**

```json
{
    "success": true
}
```

### Validation:

- **phone_number** should match the pattern `^\+[1-9]\d{1,14}$`.
- **address** should match the regex `^0x0[0-9a-fA-F]{63}$`.
- **first_name** and **last_name** should consist of alphabetic characters only, with a length between 1 and 20 characters.

### Notes:

Upon successful registration, a contract will be deployed based on the provided information.

### Example

```ts
// Import necessary modules
import fastify from 'fastify';

// Create Fastify instance
const app = fastify({ logger: true });

// Define the register endpoint
app.post('/register', async (request, reply) => {
    try {
        const { phone_number, address, first_name, last_name } = request.body;

        // Perform validation checks
        if (!phone_number.match(/^\+[1-9]\d{1,14}$/)) {
            return reply.status(400).send({ error: 'Invalid phone number format' });
        }

        if (!address.match(/^0x0[0-9a-fA-F]{63}$/)) {
            return reply.status(400).send({ error: 'Invalid StarkNet address format' });
        }

        if (!/^[A-Za-z]{1,20}$/.test(first_name)) {
            return reply.status(400).send({ error: 'Invalid first name format' });
        }

        if (!/^[A-Za-z]{1,20}$/.test(last_name)) {
            return reply.status(400).send({ error: 'Invalid last name format' });
        }

        // If validation passes, proceed with registration
        // Registration logic goes here

        // Return success response
        return { success: true };
    } catch (error) {
        // Handle errors
        console.error('Error during registration:', error);
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
});

// Start the server
app.listen(3000, '0.0.0.0', (err, address) => {
    if (err) throw err;
    console.log(`Server listening on ${address}`);
});
```

## Tasks:

- [ ] Implement the /register endpoint.
- [ ] Validate the request body parameters.
- [ ] Validate the registration when the contract is deployed.

**Comment by ocdbytes** [comment]
hey @LucasLvy can you assign this issue to me ?

**Comment by Dprof-in-tech** [comment]
hey @LucasLvy 
Please i would love to work on this

**Comment by mubarak23** [comment]
@LucasLvy if @ocdbytes is occupied, i will like to tackle this issue

**Comment by LucasLvy** [comment]
Hey this endpoint is done
