### ISSUE TITLE
Implement /transaction_history Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#31]
## Description

We need to implement the `/transaction_history` endpoint in the Vault backend. This endpoint is responsible for retrieving transaction history for a specific account.

## Details

- **Method:** GET
- **Path:** /transaction_history
- **Summary:** Retrieve transaction history for a specific account.

### Request Parameters:

- **address:** The StarkNet address for which transaction history is to be retrieved.

- **pagination:** (Optional) An integer specifying the pagination page number.

### Response:

- **Status Code:** 200
- **Description:** List of transactions
- **Content Type:** application/json
- **Body:**

```json
{
  "page_count": 5,
  "transactions": [
    {
      "amount": "0x123456789012345678",
      "from": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
      "hash": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
      "name": "Other User 1"
    },
    {
      "amount": "0x987654321098765432",
      "to": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
      "hash": "0xABCDEF0123456789abcdef0123456789abcdefABCDEF0123456789abcdef0123",
      "name": "Other User 2"
    }
  ]
}
```

### Validation:

- **address** should match the regex `^0x0[0-9a-fA-F]{63}$`.
- **pagination** should be an integer.

### Notes:

- The transaction history will be paginated, with each page containing a specified number of transactions.
- The `page_count` field indicates the total number of pages available for pagination.

## Suggested Implementation (using TypeScript and Fastify):

```typescript
// Import necessary modules
import fastify from 'fastify';

// Create Fastify instance
const app = fastify({ logger: true });

// Define the transaction_history endpoint
app.get('/transaction_history', async (request, reply) => {
    try {
        // Mocked transaction history data
        const transactionHistory = [
            {
                amount: "0x123456789012345678",
                from: "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
                hash: "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
                name: "Other User 1"
            },
            {
                amount: "0x987654321098765432",
                to: "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD",
                hash: "0xABCDEF0123456789abcdef0123456789abcdefABCDEF0123456789abcdef0123",
                name: "Other User 2"
            }
        ];

        // Return transaction history
        return transactionHistory;
    } catch (error) {
        // Handle errors
        console.error('Error retrieving transaction history:', error);
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
});

// Start the server
app.listen(3000, '0.0.0.0', (err, address) => {
    if (err) throw err;
    console.log(`Server listening on ${address}`);
});
```

## Tasks:

- [ ] Implement the `/transaction_history` endpoint.
- [ ] Validate the request parameters.
- [ ] Retrieve and paginate the transaction history.
- [ ] Ensure transaction history retrieval logic is functioning correctly.
