### ISSUE TITLE
Implement /get_balance Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#32]
## Description

We need to implement the `/get_balance` endpoint in the Vault backend. This endpoint is responsible for retrieving the current USD balance of an account.

## Details

- **Method:** GET
- **Path:** /get_balance
- **Summary:** Get the current USD balance of an account.

### Request Parameters:

- **address:** The Ethereum address for which the balance is to be retrieved.

### Response:

- **Status Code:** 200
- **Description:** Balance of the account.
- **Content Type:** application/json
- **Body:**

```json
{
    "balance": "0x1234567890abcdef"
}
```

### Notes:

The balance is returned as a hexadecimal string representing the USD balance of the account.

## Tasks:

- [ ] Implement the `/get_balance` endpoint.
- [ ] Retrieve the balance for the specified Ethereum address.
- [ ] Handle errors gracefully.

**Comment by EjembiEmmanuel** [comment]
@LucasLvy can I work on this?

**Comment by Dprof-in-tech** [comment]
hi @LucasLvy 
Please Assign this to me
